name: Lint Code Base
on:
  push:
    branches-ignore:
      - 'master'
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # - name: Lint Code Base
      #   uses: docker://github/super-linter:v3
      #   env:
      #     VALIDATE_ALL_CODEBASE: false
      - name: success 
        # if: success()
        run: |
          echo success
      - name: Creates local changes
        id: standard
        if: always()
        run: |
          echo ::set-output name=changes::$( echo $(npm install -g standard)) 
          npx standard --fix
      # - name: Commit files
      #   if: failure()
      #   run: |
      #     git config --global user.name 'Michael Zheng'
      #     git config --global user.email 'mzheng1@users.noreply.github.com'
      #     git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      #     git checkout "${GITHUB_REF:11}"
      #     git commit -am "Automated report"
      #     git push





# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Lint Code Base
#         uses: docker://github/super-linter:v3
#         env:
#           VALIDATE_ALL_CODEBASE: false
#       - name: Creates local changes
#         if: failure()
#         runs: |
#           npm install standard
#           standard --fix
